ArgosVetShop/ViewModels/AppointmentsViewModels/RequestAppointmentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArgosVetShop.ViewModels.AppointmentsViewModels
{
    public class RequestAppointmentViewModel
    {
        private string _date = "";
        private List<SelectListItem> _hours = null;
        [Required]
        public int petId { get; set; }
        [Required(ErrorMessage = "Selection is needed")]
        [Display(Name = "Pick Your Service")]
        public int ServiceId { get; set; }
        public List<SelectListItem> SelectItems
        {
            get {
                return new List<SelectListItem>() {
                    new SelectListItem { Value = "0", Text="Select your service" ,Selected = true, Disabled = true},
                    new SelectListItem { Value = "1" , Text = "Veterinary consultation" },
                    new SelectListItem { Value = "2" , Text = "Haircut and Bath" },
                    new SelectListItem { Value = "3" , Text = "Haircut" },
                    new SelectListItem { Value = "4" , Text = "Bath" },
                    new SelectListItem { Value = "5" , Text = "Flea Bath" },

                };
            }
        }
        [Required]
        [Display(Name = "Pick Your Date")]
        public string Date
        {
            get
            {
                if (string.IsNullOrEmpty(_date))
                {
                    _date = DateTime.Now.Date.ToString("d MMMM, yyyy");
                }
                return _date;
            }
            set
            {
                _date = value;
            }
        }

        [Required(ErrorMessage = "Selection is needed")]
        [Display(Name = "Pick Your Hour")]
        public string Hour { get; set; }
        public List<SelectListItem> Hours
        {
            get
            {
                if (_hours == null)
                {
                    _hours = new List<SelectListItem>()
                    {
                        new SelectListItem { Value = "", Text="Pick your hour", Disabled = true, Selected = true },
                        new SelectListItem { Value = "10:00AM",Text ="10:00am - 11:00am" },
                        new SelectListItem { Value = "11:00AM",Text ="11:00am - 12:00pm" },
                        new SelectListItem { Value = "12:00AM",Text ="12:00pm - 1:00pm" },
                        new SelectListItem { Value = "3:00PM",Text ="3:00pm - 4:00pm" },
                        new SelectListItem { Value = "4:00PM",Text ="4:00pm - 5:00pm" },
                        new SelectListItem { Value = "5:00PM",Text ="5:00pm - 6:00pm" },

                    };
                }
                return _hours;
                
            }
            set
            {
                _hours = value;
            }
        }

    }
}

ArgosVetShop/Controllers/UserManagmentController.cs
using ArgosVetShop.ViewModels.AppointmentsViewModels;
using ArgosVetShop.ViewModels.ManagmentViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ArgosVetShop.Controllers
{
    public class UserManagmentController:BaseController
    {
        [HttpGet]
        [Authorize(Roles = "User")]
        public async Task<ActionResult> Managment()
        {
            if (TempData["success"] != null)
            {
                ViewBag.Success = "Your Pet has been suscribed";
            }
            if (TempData["successEdit"] != null)
            {
                ViewBag.Success = "Your Pet information has been updated";
            }
            if (TempData["successBooked"] != null)
            {
                ViewBag.Success = "Your appointment has been booked";
            }
            var viewModel = await UserService.GetUserInformation(User.Identity.GetUserId());
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "User")]
        public ActionResult AddPet()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "User")]
        [ValidateAntiForgeryToken()]
        public async Task<ActionResult> AddPet(PetViewModel viewModel,HttpPostedFileBase photo)
        {
            if (ModelState.IsValid)
            {
                viewModel.OwnerId = User.Identity.GetUserId();
                var userName = User.Identity.Name;
                var route = Directory.CreateDirectory(Server.MapPath("~/Content/img/photos/" + userName));            
                var success = await UserService.SuscribePet(viewModel, photo, route);
                if(success){
                    TempData["success"] = "success";
                    return RedirectToAction("Managment");
                }
                else
                {
                    ViewBag.Failed = "An error occurred please contact the administrator";
                }
            }
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "User")]
        public async Task<ActionResult> EditPet(int petId)
        {
            var viewModel = await UserService.GetPetInformation(petId);
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "User")]
        [ValidateAntiForgeryToken()]
        public async Task<ActionResult> EditPet(PetViewModel viewModel, HttpPostedFileBase photo)
        {
            if (ModelState.IsValid)
            {
                var userName = User.Identity.Name;
                var route = Server.MapPath("~/Content/img/photos/" + userName);
                var success = await UserService.EditPetInformation(viewModel, photo, route);
                if (success)
                {
                    TempData["successEdit"] = "success";
                    return RedirectToAction("Managment");
                }
                else
                {
                    ViewBag.Failed = "An error ocurred during update";
                }
            }
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "User")]
        public ActionResult RequestAppointment(int petId)
        { 
            var viewModel = new RequestAppointmentViewModel();
            viewModel.petId = petId;
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles ="User")]
        [ValidateAntiForgeryToken()]
        public async Task<ActionResult> RequestAppointment(RequestAppointmentViewModel viewModel)
        {
            if (ModelState.IsValid && viewModel.ServiceId > 0)
            {
                var outCome = await UserService.RequestAppointment(viewModel);
                if(outCome.GetType() == typeof(string))
                {
                    var code = outCome as string;
                    switch (code)
                    {
                        case "Date Booked":
                            TempData["successBooked"] = "success";
                            return RedirectToAction("Managment");
                        case "Date Not Available":
                            ViewBag.DateNotAvailable = "No appointments available for this date";
                            return View(viewModel);
                        case "Error":
                            ViewBag.Failed = "An error has ocurred pleas ";
                            return View(viewModel);
                    }
                }
                else if(outCome.GetType() == typeof(RequestAppointmentViewModel))
                {
                    var updatedViewModel = outCome as RequestAppointmentViewModel;
                    ViewBag.HourTaken = "The Hour has been already taken";
                    return View(updatedViewModel);
                }
            }
            if(viewModel.ServiceId <= 0)
            {
                ViewBag.PickService = "Selection is needed";
            }
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles ="User")]
        public async Task<ActionResult> PetRecord(int petId)
        {
            var viewModel = await UserService.GetPetInformation(petId);
            if (!string.IsNullOrEmpty(viewModel.petPhotoURL))
            {
                var image = viewModel.petPhotoURL;
                var userName = User.Identity.Name;
                var route = UrlHelper.GenerateContentUrl("~/Content/img/photos/" + userName, HttpContext);
                viewModel.petPhotoURL = Path.Combine(route, image);
            }
            return View(viewModel);
        }

    }
}

ArgosVetShop/Views/UserManagment/AddPet.cshtml
@model ArgosVetShop.ViewModels.ManagmentViewModels.PetViewModel
@{
    ViewBag.Title = "AddPet";
}

<section id="PetForm">
    <div class="container">
        <div class="row">
            <h5>Suscribe your pet</h5>
        </div>
        <div class="row">
            <div class="col s12 m12 l12">
                <div class="card hoverable">
                    <div class="card-content">
                        <div class="row">
                            @using (Html.BeginForm("AddPet","UserManagment",FormMethod.Post,new { role="form", enctype="multipart/form-data",@class="col s12 m12 l12" }))
                            {
                                @Html.AntiForgeryToken()
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.petName)
                                    @Html.TextBoxFor(m => m.petName)
                                    @Html.ValidationMessageFor(m => m.petName, "",new { @class="text-danger"})
                                </div>
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.petLastName)
                                    @Html.TextBoxFor(m => m.petLastName)
                                    @Html.ValidationMessageFor(m => m.petLastName, "", new { @class = "text-danger" })
                                </div>
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.petAge)
                                    @Html.TextBoxFor(m => m.petAge)
                                    @Html.ValidationMessageFor(m => m.petAge, "", new { @class = "text-danger" })
                                </div>
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.petType)
                                    @Html.TextBoxFor(m => m.petType)
                                    @Html.ValidationMessageFor(m => m.petType,"", new { @class="text-danger"})
                                </div>
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.petBreed)
                                    @Html.TextBoxFor(m => m.petBreed)
                                    @Html.ValidationMessageFor(m => m.petBreed, "", new { @class = "text-danger" })
                                </div>
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.petColor)
                                    @Html.TextBoxFor(m => m.petColor)
                                    @Html.ValidationMessageFor(m => m.petColor, "", new { @class = "text-danger" })
                                </div>
                                <div class="col s12">
                                    
                                        @Html.LabelFor(m => m.petGender)
                                    <p>
                                        @Html.RadioButton("petGender","Male",true,new{ @id="genderMale", @value="Male", @class="with-gap" })
                                        <label for="genderMale">Male</label>
                                    </p>
                                    <p>
                                        @Html.RadioButton("petGender", "Female",false, new { @id = "genderFemale", @value = "Female", @class = "with-gap" })
                                        <label for="genderFemale">Female</label>
                                    </p>
                                </div>
                                
                                <div class="col s12">
                                    <div class="file-field input-field">
                                        <div class="btn teal darken-3">
                                            <span>
                                                Upload Photo
                                            </span>
                                            <input type="file" name="photo">
                                        </div>
                                        <div class="file-path-wrapper">
                                            @Html.TextBoxFor(m => m.petPhotoURL, new { @class = "file-path validate", @type = "text" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col s4 offset-s8 ">
                                        <button type="submit" class="btn waves-effect waves-light teal darken-3" value="AddPet">
                                            SUSCRIBE <i class="material-icons right">send</i>
                                        </button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        if ('@ViewBag.Success') {
            Materialize.toast('@ViewBag.Success', 3000, 'success')
        } if ('@ViewBag.Failed') {
            Materialize.toast('@ViewBag.Failed', 3000, 'danger')
        }
    </script>
}


ArgosVetShop/Views/UserManagment/EditPet.cshtml
@model ArgosVetShop.ViewModels.ManagmentViewModels.PetViewModel
@{
    ViewBag.Title = "EditPet";
}

<section id="PetForm">
    <div class="container">
        <div class="row">
            <h5>Edit your pet Information</h5>
        </div>
        <div class="row">
            <div class="col s12 m12 l12">
                <div class="card hoverable">
                    <div class="card-content">
                        <div class="row">
                            @using (Html.BeginForm("EditPet", "UserManagment", FormMethod.Post, new { role = "form", enctype = "multipart/form-data", @class = "col s12 m12 l12" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.HiddenFor(m => m.OwnerId)
                                @Html.HiddenFor(m => m.petId)
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.petName)
                                    @Html.TextBoxFor(m => m.petName)
                                    @Html.ValidationMessageFor(m => m.petName, "", new { @class = "text-danger" })
                                </div>
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.petLastName)
                                    @Html.TextBoxFor(m => m.petLastName)
                                    @Html.ValidationMessageFor(m => m.petLastName, "", new { @class = "text-danger" })
                                </div>
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.petAge)
                                    @Html.TextBoxFor(m => m.petAge)
                                    @Html.ValidationMessageFor(m => m.petAge, "", new { @class = "text-danger" })
                                </div>
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.petType)
                                    @Html.TextBoxFor(m => m.petType)
                                    @Html.ValidationMessageFor(m => m.petType, "", new { @class = "text-danger" })
                                </div>
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.petColor)
                                    @Html.TextBoxFor(m => m.petColor)
                                    @Html.ValidationMessageFor(m => m.petColor, "", new { @class = "text-danger" })
                                </div>
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.petBreed)
                                    @Html.TextBoxFor(m => m.petBreed)
                                    @Html.ValidationMessageFor(m => m.petBreed, "", new { @class = "text-danger" })
                                </div>
                                <div class="col s12">

                                    @Html.LabelFor(m => m.petGender)
                                    <p>
                                        @Html.RadioButton("petGender","Male",Model.IsMale, new { @id = "genderMale", @value = "Male", @class = "with-gap" })
                                        <label for="genderMale">Male</label>
                                    </p>
                                    <p>
                                        @Html.RadioButton("petGender", "Female", Model.IsFemale,new { @id = "genderFemale", @value = "Female", @class = "with-gap" })
                                        <label for="genderFemale">Female</label>
                                    </p>
                                </div>
                                
                                <div class="col s12">
                                    <div class="file-field input-field">
                                        <div class="btn teal darken-3">
                                            <span>
                                                Upload Photo
                                            </span>
                                            <input type="file" name="photo">
                                        </div>
                                        <div class="file-path-wrapper">
                                            @Html.TextBoxFor(m => m.petPhotoURL, new { @class = "file-path validate", @type = "text" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col s4 offset-s8 ">
                                        <button type="submit" class="btn waves-effect waves-light teal darken-3" value="AddPet">
                                            CONFIRM <i class="material-icons right">send</i>
                                        </button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        if ('@ViewBag.Success') {
            Materialize.toast('@ViewBag.Success', 3000, 'success')
        } if ('@ViewBag.Failed') {
            Materialize.toast('@ViewBag.Failed', 3000, 'danger')
        }
    </script>
}



ArgosVetShop/Views/UserManagment/Managment.cshtml
@model ArgosVetShop.ViewModels.ManagmentPresentationViewModel
@{
    ViewBag.Title = "Managment";
}

<section id="UserManagment">
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h2>Welcome! @Model.User.FullName</h2>
            </div>
        </div>
        <div class="row">
            <div class="col s12 m12 l12 center">
                <p class="bold">
                    Now you can suscribe your pets to our system to make appointments and keep a record of every service
                </p>
            </div>
        </div>
        <div class="row">
            <div class="row">
                <div class="col s6 m8 l8">
                    <h3 class="left no-margin">Your Pets</h3>
                </div>
                <div class="col s6 m4 l4">
                    <a class="btn-floating btn-large waves-effect waves-light teal darken-3 right tooltipped" data-position="right" data-delay="50" data-tooltip="Suscribe Pet" href="@Url.Action("AddPet","UserManagment")"><i class="material-icons">add</i></a>
                </div>
            </div>
            @if (Model.Pets.Any())
            {
                <div class="row">
                    @foreach (var pet in Model.Pets)
                    {
                    <div class="col s12 m6 l6">
                        <div class="card hoverable">
                            <div class="card-image">
                                @if (string.IsNullOrEmpty(@pet.petPhotoURL))
                                {
                                    <img class="respnsive-img" src="~/Content/img/assets/nophoto.png" />
                                    <h5 class="card-title black-text">@pet.petName</h5>
                                }
                                else
                                {
                                    <img class="respnsive-img" src="@pet.petPhotoURL" />
                                    <h5 class="card-title">@pet.petName</h5>
                                }
                               
                                <a class="btn-floating btn-large halfway-fab waves-effect waves-light teal darken-3" href="@Url.Action("EditPet",new{ petId = pet.petId })"><i class="material-icons">edit</i></a>
                            </div>
                            <div class="card-content">
                                <div class="row no-bottom-margin">
                                    <div class="col s6 m6 l6 center">
                                        <span class="bold">Age:</span>
                                    </div>
                                    <div class="col s6 m6 l6">
                                        @pet.petAge
                                    </div>
                                </div>
                                <div class="row no-bottom-margin">
                                    <div class="col s6 m6 l6 center">
                                        <span class="bold">Breed:</span>
                                    </div>
                                    <div class="col s6 m6 l6">
                                        @pet.petBreed
                                    </div>
                                </div>

                                <div class="row no-bottom-margin">
                                    <div class="col s6 m6 l6 center">
                                        <span class="bold">Type:</span>
                                    </div>
                                    <div class="col s6 m6 l6">
                                        @pet.petType
                                    </div>
                                </div>

                            </div>
                            <div class="card-action center">
                                    <a class="bold teal-text text-darken-3" href="@Url.Action("PetRecord",new { petId = pet.petId})">RECORD</a>
                                    <a class="bold teal-text text-darken-3" href="@Url.Action("RequestAppointment",new { petId = pet.petId })">REQUEST APPOINTMENT</a>
                            </div>
                        </div>
                    </div>

                    }
                </div>
            }
            else
            {
                <div class="row">
                    <h5>No Pets suscribed to our system push the add button to suscribe a pet</h5>
                </div>
            }
        </div>
    </div>
</section>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        if ('@ViewBag.Success') {
            Materialize.toast('@ViewBag.Success', 3000, 'success')
        } if ('@ViewBag.Failed') {
            Materialize.toast('@ViewBag.Failed', 3000, 'danger')
        }
    </script>
}

ArgosVetShop/Views/UserManagment/RequestAppointment.cshtml
@model ArgosVetShop.ViewModels.AppointmentsViewModels.RequestAppointmentViewModel
@{
    ViewBag.Title = "RequestAppointment";
}

<section id="PetForm">
    <div class="container">
        <div class="row">
            <h5>Request an Appointment</h5>
        </div>
        <div class="row">
            <div class="col s12 m12 l12">
                <div class="card hoverable">
                    <div class="card-content">
                        <div class="row">
                            @using (Html.BeginForm("RequestAppointment", "UserManagment", FormMethod.Post, new { role = "form", @class = "col s12 m12 l12" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.HiddenFor(m => m.petId)
                                <div class="row">
                                    <div class="col s12">
                                        @Html.LabelFor(m => m.ServiceId)
                                        @Html.DropDownListFor(m => m.ServiceId, Model.SelectItems)
                                        <span class="text-danger">@ViewBag.PickService</span>
                                    </div>
                                    <div id="price-tag" class="col s12">

                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col s8">
                                        @Html.LabelFor(m => m.Date)
                                        @Html.TextBoxFor(m => m.Date, new { @class = "datepicker" })
                                        @Html.ValidationMessageFor(m => m.Date, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col s4">
                                        @Html.LabelFor(m => m.Hour)
                                        @Html.DropDownListFor(m => m.Hour, Model.Hours)
                                        @Html.ValidationMessageFor(m => m.Hour, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col s4 offset-s8 ">
                                        <button type="submit" class="btn waves-effect waves-light teal darken-3" value="AddPet">
                                           REQUEST <i class="material-icons right">send</i>
                                        </button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $('#ServiceId').change(function () {
                var serviceId = parseInt($(this).val());
                switch (serviceId) {
                    case 1:
                        $('#price-tag').html('');
                        $('#price-tag').html('<span class="bold">Price: </span> <span>$50.00</span>');
                        break;
                    case 2:
                        $('#price-tag').html('');
                        $('#price-tag').html('<span class="bold">Price: </span> <span>$230.00</span>');
                        break;
                    case 3:
                        $('#price-tag').html('');
                        $('#price-tag').html('<span class="bold">Price: </span> <span>$150.25</span>');
                        break;
                    case 4:
                        $('#price-tag').html('');
                        $('#price-tag').html('<span class="bold">Price: </span> <span>$100.25</span>');
                        break;
                    case 5:
                        $('#price-tag').html('');
                        $('#price-tag').html('<span class="bold">Price: </span> <span>$150.50</span>');
                        break;
                    default:
                        $('#price-tag').html('');
                }
            });


        });



        if ('@ViewBag.Success') {
            Materialize.toast('@ViewBag.Success', 3000, 'success')
        } if ('@ViewBag.Failed') {
            Materialize.toast('@ViewBag.Failed', 3000, 'danger')
        } if ('@ViewBag.DateNotAvailable') {
            Materialize.toast('@ViewBag.DateNotAvailable', 5000, 'warning')
        } if ('@ViewBag.HourTaken') {
            Materialize.toast('@ViewBag.HourTaken', 5000, 'warning')
        }
    </script>
}