ArgosVetShop/ViewModels/ManagmentViewModels/VetManagmentViewModel.cs
using ArgosVetShop.ViewModels.AppointmentsViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ArgosVetShop.ViewModels.ManagmentViewModels
{
    public class VetManagmentViewModel
    {
        public List<AppointmentViewModel> TodayAppointments { get; set; }
        public List<AppointmentViewModel> FutureAppoitments { get; set; }
        public List<AppointmentViewModel> PastAppointments { get; set; }
    }
}

ArgosVetShop/Controllers/VetManagmentController.cs
using ArgosVetShop.ViewModels.AppointmentsViewModels;
using ArgosVetShop.ViewModels.ManagmentViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ArgosVetShop.Controllers
{
    public class VetManagmentController:BaseController
    {
        [HttpGet]
        [Authorize(Roles = "Veterinarian")]
        public async Task<ActionResult> AppointmentManagment()
        {
            if (TempData["success"] != null)
            {
                ViewBag.Success = "The appointment information was updated";
            }

            var viewModel = new VetManagmentViewModel();
            viewModel.TodayAppointments = await VetService.GetTodayAppoinments();
            viewModel.PastAppointments = await VetService.GetPastAppoitnments();
            viewModel.FutureAppoitments = await VetService.GetFutureAppoitnments();
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Veterinarian")]
        public ActionResult AddInformation(int appointmentId)
        {
            var viewModel = new AddAppointmentInformationViewModel();
            viewModel.AppointmentId = appointmentId;
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Veterinarian")]
        [ValidateAntiForgeryToken()]
        public async Task<ActionResult> AddInformation(AddAppointmentInformationViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var success = await VetService.UpdateAppointmentInformation(viewModel);
                if (success)
                {
                    TempData["success"] = "success";
                    return RedirectToAction("AppointmentManagment");
                }
            }
            ViewBag.Failed = "Something went wrong with the update";
            return View(viewModel);
        }

    }
}

ArgosVetShop/Views/VetManagment/AddInformation.cshtml
@model ArgosVetShop.ViewModels.AppointmentsViewModels.AddAppointmentInformationViewModel
@{
    ViewBag.Title = "AddInformation";
}

<section id="AppointmentInformationForm">
    <div class="container">
        <div class="row">
            <h5>Add a Diagnostic and observation</h5>
        </div>
        <div class="row">
            <div class="col s12 m12 l12">
                <div class="card hoverable">
                    <div class="card-content">
                        <div class="row">
                            @using (Html.BeginForm("AddInformation", "VetManagment", FormMethod.Post, new { role = "form", @class = "col s12 m12 l12" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.HiddenFor(m => m.AppointmentId)
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.Diagnostic)
                                    @Html.TextAreaFor(m => m.Diagnostic,new { @class = "materialize-textarea" })
                                    @Html.ValidationMessageFor(m => m.Diagnostic, "", new { @class = "text-danger" })
                                </div>
                                <div class="input-field col s12">
                                    @Html.LabelFor(m => m.Observation)
                                    @Html.TextAreaFor(m => m.Observation,new { @class = "materialize-textarea"})
                                    @Html.ValidationMessageFor(m => m.Observation, "", new { @class = "text-danger" })
                                </div>
                                <div class="row">
                                    <div class="col s4 offset-s8 ">
                                        <button type="submit" class="btn waves-effect waves-light teal darken-3" value="AddPet">
                                            SUBMIT <i class="material-icons right">send</i>
                                        </button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


